### ISSUE TITLE
Release to rubygems.org

### ISSUE THREAD

**Issue by masutaka** [kyanny/compare_linker#31]
Hi kyanny-san,

Will you release to https://rubygems.org?
I want to use in my gem. But can't write the following...

```ruby
spec.add_dependency 'compare_linker', github: 'kyanny/compare_linker'
# or
spec.add_dependency 'compare_linker', git: 'git@github.com:kyanny/compare_linker.git'
```

**Comment by kyanny** [comment]
@masutaka さん、お待たせしてすいません。いろいろ考えていたのですが、悩んでしまい、時間がかかってしまいました。

Rubygems.org に公開するのはちょっとためらっています。理由は、

- 名前が気に入っていない
- 現在アクティブに開発していない状況で公開するのは気がひける

の二点です。

確認ですが、 bundler 経由で利用する形ではなく、 gemspec に依存を書く必要があるということですよね？

僕自身は上記のとおり Rubygems.org での公開にはあまり積極的になれないのですが、せっかく使いたいといってくださってるのを邪魔してしまうのも本意ではありません。

そこで提案なのですが、もしよければ masutaka さんご自身で Rubygems.org に公開しませんか？リポジトリは fork していただいても良いですし、このリポジトリのコラボレーターになってもらって自由に使っていただくのでも構いません。

**Comment by masutaka** [comment]
@kyanny さん、ご丁寧にありがとうございます！
このリポジトリをforkして公開します。

**Comment by masutaka** [comment]
@kyanny  さん、Releaseさせて頂きました。
https://rubygems.org/gems/compare_linker

いくつかバグを見つけたので、修正していきます。
ありがとうございました！
