### ISSUE TITLE
SSH URL is not supported in LockfileComparator.compare method

### ISSUE THREAD

**Issue by 7coAim** [kyanny/compare_linker#35]
# Issues:

SSH URL is not supported in LockfileComparator.compare method

* HTTPS URL：supported
`https://github.com/owner/gem_name.git`

* SSH URL：not supported 
`git@github.com:owner/gem_name.git`

→ Can not read remote URL in the following cases ...
Gemfile.lock:
```
GIT
  remote: git@github.com:owner/gem_name.git
  revision: 3a748332bade386c88..........
  branch: master
  specs:
    XXXXX (1.0.0)
```

# Code:

https://github.com/kyanny/compare_linker/blob/cc5c7b25abe68dec2843138914bca1d9d2b829bf/lib/compare_linker/lockfile_comparator.rb#L16

Regular expression modified code:
```
/github\.com[:\/]([^\/]+)\/([^.]+)/
```

**Comment by kyanny** [comment]
Hello @7coAim
Thank you for sending PR to compare_linker!

Unfortunately, I no longer maintain this project.
Now @masutaka's fork is the most active one.
https://github.com/masutaka/compare_linker

Could you send PR to his forked repo?
